services:
  ubuntu:
    image: nginx-learning-snapshot
    # build: .
    container_name: nginx-learning
    privileged: true
    command: /lib/systemd/systemd
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890"
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    # volumes:
    #   - ./nginx/config:/etc/nginx
    #   - ./nginx/logs:/var/log/nginx
    #   - ./nginx/html:/var/www/html
    networks:
      - backend

  app1:
    image: traefik/whoami
    container_name: app1
    networks:
      - backend

  app2:
    image: traefik/whoami
    container_name: app2
    networks:
      - backend

  app3:
    image: traefik/whoami
    container_name: app3
    networks:
      - backend

networks:
  backend:
    driver: bridge
