user www-data;

worker_processes auto;

events {
  worker_connections 1024;
}

http {

  include mime.types;

  # Buffer size for POST submissions
  client_body_buffer_size 10K;
  client_max_body_size 8m;

  # Buffer size for Headers
  client_header_buffer_size 1k;

  # Max time to receive client headers/body (não se refere ao body inteiro, mas a um chunk lido para o buffer) - default 70
  #medidos em segundos
  client_body_timeout 12;
  client_header_timeout 12;

  # Max time to keep a keepalive connection open for (caso o cliente (browser)esteja prestes a mandar mais dados) 
  keepalive_timeout 15; # Aqui especificado em milissegundos, Default é 60s

  # Max time for the client accept/receive a response
  send_timeout 10;

  #As duas abaixo atual em conjunto para melhorar a performance servindo arquivos estáticos
  #Não se usa buffering em memória, le direto do disco e envia para a rede.
  #tcp_nopush otimiza o tamanho dos pacotes conforme os dados a serem enviados
  # ----------------------
  # Skip buffering for static files
  sendfile on;

  # Optimise sendfile packets
  tcp_nopush on;
  # ----------------------
  
  server {

    listen 80;
    server_name localhost;

    root /var/www/demo;

    index index.php index.html;

    location / {
      try_files $uri $uri/ =404;
    }

    location ~\.php$ {
      # Pass php requests to the php-fpm service (fastcgi)
      include fastcgi.conf;
      fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

  }
}
